#!/bin/sh

#
# Check DKMS installation
#
dkms status
dkms status -k $(uname -r) | grep -q ": installed"
if [ $? -ne 0 ]; then
	echo "DKMS installation: failed for $(uname -r)!"
	exit 1
fi
echo "DKMS installation: OK"

#
# Load the base DAHDI module
#
modprobe -r dahdi
modprobe dahdi

if [ $? -ne 0 ]; then
	echo "DAHDI module load: failed!"
	exit 1
fi
echo "DAHDI module load: OK"

exit 0

