#!/bin/sh

#
# Check DKMS installation
#
dkms status
dkms status -k $(uname -r) | grep -q ": installed"
if [ $? -ne 0 ]; then
	echo "DKMS installation: failed for $(uname -r)!"
	exit 1
fi
echo "DKMS installation: OK"

#
# Load all the DAHDI modules:
#

set -e

# dahdi_vpmadt032_loader is architecture-dependent
modules=`awk -F'"' '/^BUILT_MODULE_NAME/ {print $2}' debian/dkms.conf | grep -v dahdi_vpmadt032_loader`

echo "Unloading any existing modules:"
/usr/share/dahdi/dahdi-modules unload
echo "Loading all modules: $modules"
for module in $modules; do
	modprobe $module
done

echo "Unloading them all again"
/usr/share/dahdi/dahdi-modules unload
modprobe -r echo

# uninstall, to not get in the way of the m-a test
dkms uninstall dahdi/`dkms status dahdi | cut -d, -f2 | head -n1` --all

echo "DAHDI modules load: OK"

exit 0

